apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app-deployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: weather-app-pod
  template:
    metadata:
      labels:
        app: weather-app-pod
    spec:
      containers:
        - name: weather-app
          image: gcr.io/PROJECT_ID/app-weather:SHORT_SHA
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: weather-config
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: weather-config
                  key: redis_port
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: weather-app-lb-service
spec:
  type: LoadBalancer
  selector:
    app: weather-app-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080